### ISSUE TITLE
избыточные проперти

### ISSUE THREAD

**Issue by dzhivushko** [PitGarin/JD1#14]
https://github.com/PitGarin/JD1/blob/101a0eaefac4986e263b20c5c2b51f406bb88a85/src/com/itacademy/jd1/homework/task22/TimeInterval.java#L3-L44
на самом деле хранить часы и минуты - это лишнее. сохранить надо было только секунды. а когда надо вернуть часы и минуты - вот там их высчитывать. хранить их незачем

**Comment by PitGarin** [comment]
По условию промежуток задается 3мя свойствами. Или я не так что то понял?

**Comment by dzhivushko** [comment]
а я не имею ничего против того, чтобы он задавался 3мя свойствами(параметры конструктора), но хранить все 3 - излишне. проще перевести в секунды и хранить только их (как сделано в JDK для Date)
