### ISSUE TITLE
название свойства

### ISSUE THREAD

**Issue by dzhivushko** [PitGarin/JD1#16]
https://github.com/PitGarin/JD1/blob/101a0eaefac4986e263b20c5c2b51f406bb88a85/src/com/itacademy/jd1/homework/task24/Appliances.java#L9

isOn - это типичное название boolean метода. но никак не свойства. свойство должно быть просто on

**Comment by PitGarin** [comment]
В методичке isOn свойство, void on(), void off() методы.

**Comment by dzhivushko** [comment]
это не одно и то же. в методичке была задача показать простейший пример свойства и методов. по сути там просто перевели с русского языка на английский - чтобы было понятно.

в дальнейшем надо ориентироваться требованиями к созданию  java beans, а не к тому примеру из методички. поэтому тут должно быть 

private boolean enabled;

public boolean getEnabled();
public void setEnabled(); 


и кстати почему у тебя методы protected, а не public?
