### ISSUE TITLE
множественное число в названии класса. только одиночное!!!

### ISSUE THREAD

**Issue by dzhivushko** [PitGarin/JD1#17]
https://github.com/PitGarin/JD1/blob/101a0eaefac4986e263b20c5c2b51f406bb88a85/src/com/itacademy/jd1/homework/task24/Appliances.java#L3

**Comment by PitGarin** [comment]
метода?

**Comment by dzhivushko** [comment]
http://prntscr.com/hrf3g4
может у меня другой гугл

**Comment by dzhivushko** [comment]
сорри, я ошибся. увидел у еще одного человека опять Appliances И еще раз полез проверять, что это слово значит.  Похоже есть и appliances и appliance. и то и другое обозначает "техника" и "прибор". надо в настоящие словари лезть, чтобы докапаться до истины. гугл действительно предлагает вариант с "s" на конце. хотя и без него тоже переводит одинаково
